name: main

on: [push]

jobs:
  styles:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: |
          wget https://github.com/google/google-java-format/releases/download/google-java-format-1.7/google-java-format-1.7-all-deps.jar
          find src -name '*.java' | xargs java -jar google-java-format-1.7-all-deps.jar -n --set-exit-if-changed
        
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
